export const metadata = {
    title: 'About || Ranjit',
    description: 'About page description Generated by create next app',
  }
const layout = ({children}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default layout;