// export const metadata = {
//     title: 'About || Ranjit',
//     description: 'About page description Generated by create next app',
//   }

  export const metadata = {
    title:"Contact || Ranjit",
    description:"Contact Description",
  }

const layout = ({children}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default layout;